## U2 Assignment {.unnumbered}
**Deadline: April 28, 2026**

[Example Notebook](https://colab.research.google.com/drive/115BsrFH6wFSOzQFQqkKwsF0twA_bezSQ?usp=sharing)

**To copy this code and run it yourself, click the link above and navigate: "file \> save a copy in Drive"**

### Errors you might Encounter:

If you encounter any of the following errors when trying to run the colab notebook, try these troubleshoots.

-   Max Retries Exceeded: Sometimes caused by running some code chunks, pausing, and then running others. Wait a few minutes, then Do 'Runtime \> Restart Session and Run All'
-   Content not found: For each statement `time.sleep(10)` change the 10 to 20.

### Exercise

1.  Read through the Colab notebook.
2.  If you have a website from your own project that you are interested in scraping, you may develop your own scraping code and present it in the interactive sessions. You may also share it with the course instructor and ask for feedback.
3.  If you don't have an example from your own project, here is a collection of example websites for scraping: https://webscraper.io/test-sites. You may build your own web scraper, or if you'd like an assigned task, try to extract the name and price of each laptop found on this site. You will need to press the 'more' button via your scraper bot to do this.
